from __future__ import annotations

from typing import Protocol

from trading_bot.core.domain.position import Position
from trading_bot.core.domain.trade import ActiveTrade, TradePlan


class IBroker(Protocol):
    def place_trade(self, plan: TradePlan) -> ActiveTrade: ...
    def advance_stage(self, trade: ActiveTrade) -> ActiveTrade: ...
    def update_stop_loss(self, trade: ActiveTrade, new_sl: float) -> ActiveTrade: ...
    def close_position(self, symbol: str) -> dict: ...
    def get_price(self, symbol: str) -> float: ...
    def get_open_orders(self, symbol: str | None = None) -> list[dict]: ...
    def get_balance(self) -> dict[str, dict]: ...
    def get_positions(self, symbol: str | None = None) -> list[Position]: ...
    def cancel_order(self, symbol: str, order_id: int) -> dict: ...
