"""extend_positions_add_trade_stages

Revision ID: af285bc12f61
Revises: b9cd2dcd8466
Create Date: 2026-06-30 15:02:41.103979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af285bc12f61'
down_revision: Union[str, Sequence[str], None] = 'b9cd2dcd8466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('next_stop_loss', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_stages_account_id'), 'trade_stages', ['account_id'], unique=False)
    op.create_index(op.f('ix_trade_stages_position_id'), 'trade_stages', ['position_id'], unique=False)
    op.add_column('positions', sa.Column('current_stage', sa.Integer(), nullable=False))
    op.add_column('positions', sa.Column('current_sl_order_id', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('current_tp_order_id', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('leverage', sa.Integer(), nullable=False))
    op.add_column('positions', sa.Column('liquidation_price', sa.Numeric(precision=28, scale=10), nullable=True))
    op.add_column('positions', sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=10), nullable=False))
    op.add_column('positions', sa.Column('margin_type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'margin_type')
    op.drop_column('positions', 'unrealized_pnl')
    op.drop_column('positions', 'liquidation_price')
    op.drop_column('positions', 'leverage')
    op.drop_column('positions', 'current_tp_order_id')
    op.drop_column('positions', 'current_sl_order_id')
    op.drop_column('positions', 'current_stage')
    op.drop_index(op.f('ix_trade_stages_position_id'), table_name='trade_stages')
    op.drop_index(op.f('ix_trade_stages_account_id'), table_name='trade_stages')
    op.drop_table('trade_stages')
    # ### end Alembic commands ###
